title: Windows Phone Wiki # The title also appears in the top-left corner of the website if no logo is selected.
description: Intivate

logo: "assets/windows_phone.png" # Logo that appears in the top-left corner of the website, next to the title.

theme: just-the-docs # The Jekyll theme selected, which is Just the Docs.
color_scheme: "dark" # Dark mode chosen as the Just the Docs theme.

url: https://intwiki.filipecollura.com # Website URL.
favicon: /assets/favicons/favicon.ico

aux_links: # Buttons that appear in the top-right corner of the website.
  "contribute":
    - "//github.com/intivate/wiki-windowsphone"
  "help + support":
    - "https://int.filipecollura.com"
aux_links_new_tab: true # Determines if an aux link opens in a new tab, or replaces the existing one.

footer_content: "Nopyright &copy; 2023 <a href=\"https://filipecollura.com\">Filipe Collura.</a>" # Custom footer content, seen at the bottom-left corner of the website.

enable_copy_code_button: true # Determines whether documented code snippets can be copied.
