title: Windows Phone # Title that appears in the top-left corner of the website.

theme: just-the-docs # The Jekyll theme selected, which is Just the Docs.
color_scheme: "dark" # Dark mode chosen as the Just the Docs theme.

logo: "Assets/Logo/intivate_logo_wide19.png" # Logo that appears in the top-left corner of the website, next to the title.
favicon_ico: "Assets/Logo/Favicon/intivate_logo.ico" # Website's favicon.

url: https://intwiki.filipecollura.com # Website URL.

aux_links: # Button that appears in the top-right corner of the website, redirecting the user to this repository.
  View it on GitHub: https://github.com/Intivate/Wiki # The text of the button + the website it redirects to.
